#!/usr/bin/env node
/**
 * TradePrompt AI — Interactive Account Setup Wizard
 *
 * Usage:
 *   cd backend && npm run setup
 *   node scripts/setup-wizard.js
 *
 * With Razorpay keys:
 *   RAZORPAY_KEY_ID=rzp_test_xxx RAZORPAY_KEY_SECRET=xxx npm run setup
 */

import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import readline from 'readline';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ENV_PATH = path.join(__dirname, '..', '.env');
const ENV_EXAMPLE = path.join(__dirname, '..', '.env.example');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));

function generateSecret(bytes = 32) {
  return crypto.randomBytes(bytes).toString('hex');
}

async function razorpayRequest(keyId, keySecret, endpoint, method = 'GET', body = null) {
  const auth = Buffer.from(`${keyId}:${keySecret}`).toString('base64');
  const res = await fetch(`https://api.razorpay.com/v1${endpoint}`, {
    method,
    headers: { Authorization: `Basic ${auth}`, 'Content-Type': 'application/json' },
    body: body ? JSON.stringify(body) : undefined
  });
  const data = await res.json();
  if (!res.ok) throw new Error(data.error?.description || JSON.stringify(data));
  return data;
}

async function setupRazorpay(keyId, keySecret) {
  console.log('\n📡 Connecting to Razorpay...');
  const account = await razorpayRequest(keyId, keySecret, '/account');
  const mode = keyId.startsWith('rzp_live') ? 'LIVE' : 'TEST';
  console.log(`   ✓ Connected: ${account.email || account.id} (${mode} mode)`);

  console.log('📋 Creating subscription plan (₹100/month)...');
  const plan = await razorpayRequest(keyId, keySecret, '/plans', 'POST', {
    period: 'monthly',
    interval: 1,
    item: {
      name: 'TradePrompt AI Pro',
      amount: 10000,
      currency: 'INR',
      description: 'Monthly AI trading prompts — NSE/BSE, Forex, Crypto'
    },
    notes: { product: 'TradePrompt AI', trial_days: '3' }
  });
  console.log(`   ✓ Plan created: ${plan.id}`);

  return { planId: plan.id, mode };
}

function writeEnvFile(config) {
  const content = `# TradePrompt AI — Generated by setup wizard
# Created: ${new Date().toISOString()}

PORT=3001
NODE_ENV=${config.nodeEnv || 'development'}

# Razorpay
RAZORPAY_KEY_ID=${config.razorpayKeyId}
RAZORPAY_KEY_SECRET=${config.razorpayKeySecret}
RAZORPAY_PLAN_ID=${config.razorpayPlanId || 'plan_SET_AFTER_RAZORPAY_SETUP'}
RAZORPAY_WEBHOOK_SECRET=${config.webhookSecret || ''}

# Subscription
TRIAL_DAYS=3
SUBSCRIPTION_AMOUNT=10000
SUBSCRIPTION_CURRENCY=INR

# Security (auto-generated)
JWT_SECRET=${config.jwtSecret}
ADMIN_SECRET=${config.adminSecret}

# Your deployed backend URL (update after deploy)
API_BASE_URL=${config.apiBaseUrl}
`;
  fs.writeFileSync(ENV_PATH, content);
  console.log(`\n   ✓ Saved: ${ENV_PATH}`);
}

async function verifySetup() {
  console.log('\n🔍 Verifying setup...');
  const results = [];

  if (fs.existsSync(ENV_PATH)) {
    results.push({ ok: true, msg: '.env file exists' });
  } else {
    results.push({ ok: false, msg: '.env file missing' });
  }

  try {
    await import('dotenv/config');
    const { config } = await import('dotenv');
    config({ path: ENV_PATH });

    const keyId = process.env.RAZORPAY_KEY_ID;
    const keySecret = process.env.RAZORPAY_KEY_SECRET;

    if (keyId && keySecret && !keyId.includes('YOUR')) {
      await razorpayRequest(keyId, keySecret, '/account');
      results.push({ ok: true, msg: 'Razorpay connection OK' });
    } else {
      results.push({ ok: false, msg: 'Razorpay keys not configured (demo mode will work)' });
    }

    if (process.env.ADMIN_SECRET && process.env.ADMIN_SECRET.length > 16) {
      results.push({ ok: true, msg: 'Admin secret configured' });
    } else {
      results.push({ ok: false, msg: 'Admin secret weak or missing' });
    }
  } catch (e) {
    results.push({ ok: false, msg: `Razorpay: ${e.message}` });
  }

  results.forEach(r => console.log(`   ${r.ok ? '✓' : '⚠'} ${r.msg}`));
  return results.every(r => r.ok);
}

async function main() {
  const isDemo = process.argv.includes('--demo');
  const isVerify = process.argv.includes('--verify-only');

  if (isVerify) {
    rl.close();
    const { default: verify } = await import('./verify-setup.js');
    return;
  }

  console.log(`
╔══════════════════════════════════════════════════╗
║     ⚡ TradePrompt AI — Account Setup Wizard      ║
╚══════════════════════════════════════════════════╝
`);

  const jwtSecret = generateSecret();
  const adminSecret = generateSecret(16);

  let apiBaseUrl = 'http://localhost:3001';
  let razorpayKeyId = process.env.RAZORPAY_KEY_ID || '';
  let razorpayKeySecret = process.env.RAZORPAY_KEY_SECRET || '';
  let razorpayPlanId = process.env.RAZORPAY_PLAN_ID || '';
  let razorpayMode = 'DEMO';
  let webhookSecret = '';

  if (isDemo) {
    console.log('Running in DEMO mode (no Razorpay required)...\n');
    razorpayKeyId = 'rzp_test_DEMO';
    razorpayKeySecret = 'demo_secret';
    razorpayPlanId = 'plan_DEMO';
  } else {
    console.log('This wizard will configure:');
    console.log('  1. Backend .env file');
    console.log('  2. Razorpay subscription plan (₹100/month)');
    console.log('  3. Admin dashboard secret');
    console.log('  4. Security keys\n');

    apiBaseUrl = (await ask('Backend URL [http://localhost:3001]: ')).trim() || 'http://localhost:3001';

    const hasKeys = razorpayKeyId && razorpayKeySecret;

    if (!hasKeys) {
      console.log('\n─── RAZORPAY SETUP ───');
      console.log('Get keys from: https://dashboard.razorpay.com/app/keys');
      console.log('Use TEST keys first (rzp_test_...), then LIVE after KYC.\n');

      const skipRazorpay = (await ask('Skip Razorpay for now? (demo mode) [y/N]: ')).trim().toLowerCase();

      if (skipRazorpay !== 'y') {
        razorpayKeyId = (await ask('Razorpay Key ID (rzp_test_...): ')).trim();
        razorpayKeySecret = (await ask('Razorpay Key Secret: ')).trim();

        if (razorpayKeyId && razorpayKeySecret) {
          try {
            const result = await setupRazorpay(razorpayKeyId, razorpayKeySecret);
            razorpayPlanId = result.planId;
            razorpayMode = result.mode;
          } catch (err) {
            console.error(`\n   ✗ Razorpay error: ${err.message}`);
            console.log('   Continuing in demo mode...\n');
            razorpayKeyId = 'rzp_test_DEMO';
            razorpayKeySecret = 'demo_secret';
          }
        }
      } else {
        console.log('   → Demo mode: payments will auto-activate licenses\n');
        razorpayKeyId = 'rzp_test_DEMO';
        razorpayKeySecret = 'demo_secret';
      }
    } else {
      console.log('\n📡 Using Razorpay keys from environment...');
      try {
        const result = await setupRazorpay(razorpayKeyId, razorpayKeySecret);
        razorpayPlanId = result.planId;
        razorpayMode = result.mode;
      } catch (err) {
        console.error(`   ✗ ${err.message}`);
        if (!razorpayPlanId) razorpayPlanId = 'plan_SET_MANUALLY';
      }
    }

    console.log('\n─── WEBHOOK (configure after deploy) ───');
    webhookSecret = (await ask('Razorpay Webhook Secret (optional, press Enter to skip): ')).trim();
  }

  writeEnvFile({
    nodeEnv: apiBaseUrl.includes('localhost') ? 'development' : 'production',
    razorpayKeyId: razorpayKeyId || 'rzp_test_YOUR_KEY_ID',
    razorpayKeySecret: razorpayKeySecret || 'YOUR_KEY_SECRET',
    razorpayPlanId: razorpayPlanId || 'plan_YOUR_PLAN_ID',
    webhookSecret,
    jwtSecret,
    adminSecret,
    apiBaseUrl
  });

  rl.close();

  printSummary({ razorpayMode, razorpayPlanId, apiBaseUrl, adminSecret, jwtSecret });
}

function printSummary({ razorpayMode, razorpayPlanId, apiBaseUrl, adminSecret, jwtSecret }) {
  console.log(`
╔══════════════════════════════════════════════════╗
║                  SETUP COMPLETE ✓                 ║
╚══════════════════════════════════════════════════╝

  Razorpay Mode:  ${razorpayMode}
  Plan ID:        ${razorpayPlanId || 'Not set (demo mode)'}
  API URL:        ${apiBaseUrl}
  Admin Secret:   ${adminSecret.slice(0, 8)}...

─── NEXT STEPS ───

  1. Start backend:
     cd backend && npm run dev

  2. Test checkout:
     ${apiBaseUrl}/checkout.html

  3. Admin dashboard:
     ${apiBaseUrl}/admin
     Secret: ${adminSecret}

  4. Load extension:
     chrome://extensions → Load unpacked → extension/

  5. Add AI API key in extension Settings:
     OpenAI: https://platform.openai.com/api-keys
     Claude: https://console.anthropic.com/

  6. After deploy, set Razorpay webhook:
     URL: ${apiBaseUrl}/api/webhook/razorpay
     Events: subscription.charged, subscription.cancelled

─── SAVE THESE SECRETS ───
  ADMIN_SECRET=${adminSecret}
  JWT_SECRET=${jwtSecret}

Full guide: docs/ACCOUNT_SETUP.md
`);
}

async function mainEntry() {
  try {
    await main();
  } catch (err) {
    console.error('Setup failed:', err.message);
    rl.close();
    process.exit(1);
  }
}

mainEntry();
